
FROM softasap/ansible:ubuntu1404base

ENV container docker

# Install Ansible
RUN pip3 install ansible ansible-lint
RUN mkdir -p /etc/ansible


# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
